
# Kuberenetes secrets for storing Azure Service Principal Client ID and Client Secret
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas-azure-service-principal
  namespace: project1100-app001-mongodb-atlas-ns
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  ClientID: 'Your Service Principal Client ID'
  ClientSecret: 'Your Service Principal Client Secret'
