# Kuberenetes Secret Store for Azure Key Vault access
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mongodb-atlas-azure-secret-store
  namespace: project1100-app001-mongodb-atlas-ns
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      # azure tenant ID, see: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
      tenantId: "Your Azure Subsctiption Tenant ID"
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "Your Key Vault URL"
      authSecretRef:
        # points to the secret that contains
        # the azure service principal credentials
        clientId:
          name: mongodb-atlas-azure-service-principal
          key: ClientID
        clientSecret:
          name: mongodb-atlas-azure-service-principal
          key: ClientSecret
