# Kuberenetes External Secret to access Azure Key Vault for MongoDB ORG ID and API Keys
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-atlas-azure-external-secret-api-key
  namespace: project1100-app001-mongodb-atlas-ns
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    atlas.mongodb.com/type: credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: mongodb-atlas-azure-secret-store

  target:
    name: mongodb-atlas-secret-for-api-key
    creationPolicy: Owner

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  - secretKey: orgId
    remoteRef:
      key: secret/orgid

  # type/name of certificate in the Azure KV
  # raw value will be returned, use templating features for data processing
  - secretKey: privateApiKey
    remoteRef:
      key: secret/api-key-priv

  # explicit type and name of secret in the Azure KV
  - secretKey: publicApiKey
    remoteRef:
      key: secret/api-key-pub
