apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-atlas-azure-external-secret-db-user
  namespace: project1100-app001-mongodb-atlas-ns
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    atlas.mongodb.com/type: credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: mongodb-atlas-azure-secret-store

  target:
    name: mongodb-atlas-secret-for-database-user
    creationPolicy: Owner

  data:
  # The name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  - secretKey: password
    remoteRef:
      key: secret/admin-user-pass
