apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-atlas-azure-external-secret-webhook
  namespace: project1100-app001-mongodb-atlas-ns
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    atlas.mongodb.com/type: credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: mongodb-atlas-azure-secret-store

  target:
    name: mongodb-atlas-secret-for-webhook
    creationPolicy: Owner

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  - secretKey: webooksecret
    remoteRef:
      key: secret/webhook-secret
