apiVersion: atlas.mongodb.com/v1
kind: AtlasBackupSchedule
metadata:
  name: project1100-app001-custom-backup-schedule
  namespace: project1100-app001-mongodb-atlas-ns
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  autoExportEnabled: false
  referenceHourOfDay: 1
  referenceMinuteOfHour: 0
  restoreWindowDays: 7
  policy:
    name: project1100-app001-custom-backup-policy
    namespace: project1100-app001-mongodb-atlas-ns
